name: PR Testing

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  run-pull-request-actions:
    name: Reusable Crypto3 Testing
    uses: ./.github/workflows/pull-request-action.yml

    secrets: inherit
    with:
      targets: |
        crypto3_zk_commitment_fold_polynomial_test
        crypto3_zk_commitment_fri_test
        crypto3_zk_commitment_lpc_test
        crypto3_zk_commitment_kzg_test
        crypto3_zk_systems_plonk_placeholder_placeholder_test
        crypto3_zk_commitment_powers_of_tau_test
        crypto3_zk_commitment_proof_of_knowledge_test
        crypto3_zk_math_expression_test
        crypto3_zk_systems_plonk_plonk_constraint_test
        crypto3_zk_commitment_proof_of_knowledge_test
        crypto3_zk_transcript_transcript_test
        crypto3_zk_commitment_proof_of_work_test
