name: PR Testing

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  handle-syncwith:
    name: Call Reusable SyncWith Handler
    uses: NilFoundation/ci-cd/.github/workflows/reusable-handle-syncwith.yml@v1
    with:
      ci-cd-ref: 'v1'
    secrets: inherit

  matrix-test:
    name: Call Reusable Crypto3 Testing
    needs:
      - handle-syncwith
    uses: NilFoundation/ci-cd/.github/workflows/reusable-crypto3-testing.yml@v1.1.0
    with:
      submodules-refs: ${{ needs.handle-syncwith.outputs.prs-refs }}
      concurrency: 2  # adjust if fails with OOM

    secrets: inherit
