name: PR Testing

on:
  pull_request:
  push:
    branches:
      - master

concurrency:
  # In master we want to run for every commit, in other branches — only for the last one
  group: ${{
    ( github.ref == 'refs/heads/master' && format('{0}/{1}/{2}', github.workflow, github.ref, github.sha) )
    ||
    format('{0}/{1}', github.workflow, github.ref) }}
  cancel-in-progress: true

jobs:
  handle-syncwith:
    name: Call Reusable SyncWith Handler
    uses: NilFoundation/ci-cd/.github/workflows/reusable-handle-syncwith.yml@v1.2.1
    with:
      ci-cd-ref: 'v1.2.1'
    secrets: inherit

  test-linux:
    name: Linux Reusable Crypto3 Testing
    needs:
      - handle-syncwith
    uses: NilFoundation/crypto3/.github/workflows/reusable-submodule-testing-linux.yml@1bd56b12f410f3f1a4891076705a9261a6b1efaa

    secrets: inherit
    with:
      submodules-refs: ${{ needs.handle-syncwith.outputs.prs-refs }}
      check-names: |
        zk-clang

  # test-mac:
  #   name: Mac Reusable Crypto3 Testing
  #   needs:
  #     - handle-syncwith
  #   uses: NilFoundation/crypto3/.github/workflows/reusable-submodule-testing-mac.yml@ede1d6b903078a0aa48a6864ba465b66af4fda8b

  #   secrets: inherit
  #   with:
  #     submodules-refs: ${{ needs.handle-syncwith.outputs.prs-refs }}
  #     check-names: |
  #       algebra-clang

