name: Run tests

on:
  # Let's run it on any commit
  [push]
  # Triggers the workflow on pull request events but only for the master branch
  #pull_request:
  #  branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

env:

jobs:
  checkout:
    runs-on: [self-hosted, tests-runner]
    steps:
      - name: Run CI script
        run: |
          scripts/ci.sh
