name: Run tests

on:
  # Let's run it on any commit
  [push]
  # Triggers the workflow on pull request events but only for the master branch
  #pull_request:
  #  branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

env:
  SUITE_REPO: "NilFoundation/crypto3"
  LIB_NAME: "zk"
  CACHE_NAME: "checkout-job-cache"

jobs:
  checkout:
    runs-on: [self-hosted, tests-runner]
    steps:
      - name: Cleanup # TODO - move to scripts on runner
        run: |
          rm -rf ./suite/* || true
          mkdir ./suite || true

      - name: Checkout suite
        uses: actions/checkout@v3
        with:
          path: ./suite
          repository: ${{ env.SUITE_REPO }}
          submodules: recursive

      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          path: ./suite/libs/${{ env.LIB_NAME }}
          submodules: recursive

      - name: Run CI script
        run: |
          pwd
          find .
          cd suite
          cp libs/${{ env.LIB_NAME }}/scripts/build.sh .
          libs/${{ env.LIB_NAME }}/scripts/ci.sh

